version: 2.1
orbs:
  node: circleci/node@1.1
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    executor: node/default
    tag: '10.4'
  steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
      
